### ISSUE TITLE
怎么样去除样式里的注释

### ISSUE THREAD

**Issue by next2014** [cssmagic/stylus-playground#6]
![_20170222134731](https://cloud.githubusercontent.com/assets/7641722/23199067/fa32829a-f906-11e6-91eb-2931454698a3.png)

**Comment by cssmagic** [comment]
由于本工具提供的是一个试用环境，在代码中添加注释是为了调试之用。它生成的代码不能直接用于生产环境，如果需要清除注释，建议使用其它工具（比如 clean-css）来压缩代码。

当然你也可以修改本工具的源码，在 `gulpfile.js` 中找到 `linenos: true` 这一句，把 `true` 改成 `false` 就可以了。

**Comment by next2014** [comment]
明白~谢谢
